#!/bin/sh

set -e

if [ "$1" = configure ]; then
	if [ -z "$2" ]; then
		# if this package has been installed before, the init script
		# already stopped acpi_fakekeyd, but if we're upgrading from an
		# acpi-support package containing acpi_fakekeyd we have to
		# manually stop the daemon to be able to start it in the
		# debhelper section below

		start-stop-daemon --oknodo --stop --quiet --exec /usr/sbin/acpi_fakekeyd
	fi
fi

#DEBHELPER#

exit 0
