Document: backports-3.17.1
Title: Debian backports-3.17.1 Manual
Author: <insert document author here>
Abstract: This manual describes what backports-3.17.1 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/backports-3.17.1/backports-3.17.1.sgml.gz

Format: postscript
Files: /usr/share/doc/backports-3.17.1/backports-3.17.1.ps.gz

Format: text
Files: /usr/share/doc/backports-3.17.1/backports-3.17.1.text.gz

Format: HTML
Index: /usr/share/doc/backports-3.17.1/html/index.html
Files: /usr/share/doc/backports-3.17.1/html/*.html
