.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH rgettext 1 "2003-07-17"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
rgettext \- extract translate message
.SH SYNOPSIS
.B rgettext
input.rb -o output.pot
.br
.SH DESCRIPTION
Extract translatable string from given input ruby script files.
.SH SEE ALSO
.BR gettext (1),
/usr/share/doc/libgettext-ruby-utils/README*,
http://ponx.s5.xrea.com/hiki/ruby-gettext-translate.html
.SH AUTHOR
This manual page was converted by Tatsuki Sugiura <sugi@nemui.org>,
from README for the Debian project.
