.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH rmsgfmt 1 "2003-07-17"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
rmsgfmt \- compile message catalog to binary format
.SH SYNOPSIS
.B rmsgfmt
input.po [ -o output.mo ]
.br
.SH DESCRIPTION
Generate binary message catalog from textual translation description.
.SH SEE ALSO
.BR msgfmt (1),
/usr/share/doc/libgettext-ruby-utils/README*,
http://ponx.s5.xrea.com/hiki/ruby-gettext-translate.html
.SH AUTHOR
This manual page was converted by Tatsuki Sugiura <sugi@nemui.org>,
from README for the Debian project.
